export const timezones = [
    { name: "Abidjan", id: "Africa/Abidjan" },
    { name: "Accra", id: "Africa/Accra" },
    { name: "Addis Ababa", id: "Africa/Addis_Ababa" },
    { name: "Algiers", id: "Africa/Algiers" },
    { name: "Asmara", id: "Africa/Asmara" },
    { name: "Asmera", id: "Africa/Asmera" },
    { name: "Bamako", id: "Africa/Bamako" },
    { name: "Bangui", id: "Africa/Bangui" },
    { name: "Banjul", id: "Africa/Banjul" },
    { name: "Bissau", id: "Africa/Bissau" },
    { name: "Blantyre", id: "Africa/Blantyre" },
    { name: "Brazzaville", id: "Africa/Brazzaville" },
    { name: "Bujumbura", id: "Africa/Bujumbura" },
    { name: "Cairo", id: "Africa/Cairo" },
    { name: "Casablanca", id: "Africa/Casablanca" },
    { name: "Ceuta", id: "Africa/Ceuta" },
    { name: "Conakry", id: "Africa/Conakry" },
    { name: "Dakar", id: "Africa/Dakar" },
    { name: "Dar es Salaam", id: "Africa/Dar_es_Salaam" },
    { name: "Djibouti", id: "Africa/Djibouti" },
    { name: "Douala", id: "Africa/Douala" },
    { name: "El Aaiun", id: "Africa/El_Aaiun" },
    { name: "Freetown", id: "Africa/Freetown" },
    { name: "Gaborone", id: "Africa/Gaborone" },
    { name: "Harare", id: "Africa/Harare" },
    { name: "Johannesburg", id: "Africa/Johannesburg" },
    { name: "Juba", id: "Africa/Juba" },
    { name: "Kampala", id: "Africa/Kampala" },
    { name: "Khartoum", id: "Africa/Khartoum" },
    { name: "Kigali", id: "Africa/Kigali" },
    { name: "Kinshasa", id: "Africa/Kinshasa" },
    { name: "Lagos", id: "Africa/Lagos" },
    { name: "Libreville", id: "Africa/Libreville" },
    { name: "Lome", id: "Africa/Lome" },
    { name: "Luanda", id: "Africa/Luanda" },
    { name: "Lubumbashi", id: "Africa/Lubumbashi" },
    { name: "Lusaka", id: "Africa/Lusaka" },
    { name: "Malabo", id: "Africa/Malabo" },
    { name: "Maputo", id: "Africa/Maputo" },
    { name: "Maseru", id: "Africa/Maseru" },
    { name: "Mbabane", id: "Africa/Mbabane" },
    { name: "Mogadishu", id: "Africa/Mogadishu" },
    { name: "Monrovia", id: "Africa/Monrovia" },
    { name: "Nairobi", id: "Africa/Nairobi" },
    { name: "Ndjamena", id: "Africa/Ndjamena" },
    { name: "Niamey", id: "Africa/Niamey" },
    { name: "Nouakchott", id: "Africa/Nouakchott" },
    { name: "Ouagadougou", id: "Africa/Ouagadougou" },
    { name: "Porto", id: "Africa/Porto-Novo" },
    { name: "Sao Tome", id: "Africa/Sao_Tome" },
    { name: "Timbuktu", id: "Africa/Timbuktu" },
    { name: "Tripoli", id: "Africa/Tripoli" },
    { name: "Tunis", id: "Africa/Tunis" },
    { name: "Windhoek", id: "Africa/Windhoek" },
    { name: "Adak", id: "America/Adak" },
    { name: "Anchorage", id: "America/Anchorage" },
    { name: "Anguilla", id: "America/Anguilla" },
    { name: "Antigua", id: "America/Antigua" },
    { name: "Araguaina", id: "America/Araguaina" },
    { name: "Buenos Aires", id: "America/Argentina/Buenos_Aires" },
    { name: "Catamarca", id: "America/Argentina/Catamarca" },
    { name: "ComodRivadavia", id: "America/Argentina/ComodRivadavia" },
    { name: "Cordoba", id: "America/Argentina/Cordoba" },
    { name: "Jujuy", id: "America/Argentina/Jujuy" },
    { name: "La Rioja", id: "America/Argentina/La_Rioja" },
    { name: "Mendoza", id: "America/Argentina/Mendoza" },
    { name: "Rio Gallegos", id: "America/Argentina/Rio_Gallegos" },
    { name: "Salta", id: "America/Argentina/Salta" },
    { name: "San Juan", id: "America/Argentina/San_Juan" },
    { name: "San Luis", id: "America/Argentina/San_Luis" },
    { name: "Tucuman", id: "America/Argentina/Tucuman" },
    { name: "Ushuaia", id: "America/Argentina/Ushuaia" },
    { name: "Aruba", id: "America/Aruba" },
    { name: "Asuncion", id: "America/Asuncion" },
    { name: "Atikokan", id: "America/Atikokan" },
    { name: "Atka", id: "America/Atka" },
    { name: "Bahia", id: "America/Bahia" },
    { name: "Bahia Banderas", id: "America/Bahia_Banderas" },
    { name: "Barbados", id: "America/Barbados" },
    { name: "Belem", id: "America/Belem" },
    { name: "Belize", id: "America/Belize" },
    { name: "Blanc", id: "America/Blanc-Sablon" },
    { name: "Boa Vista", id: "America/Boa_Vista" },
    { name: "Bogota", id: "America/Bogota" },
    { name: "Boise", id: "America/Boise" },
    { name: "Buenos Aires", id: "America/Buenos_Aires" },
    { name: "Cambridge Bay", id: "America/Cambridge_Bay" },
    { name: "Campo Grande", id: "America/Campo_Grande" },
    { name: "Cancun", id: "America/Cancun" },
    { name: "Caracas", id: "America/Caracas" },
    { name: "Catamarca", id: "America/Catamarca" },
    { name: "Cayenne", id: "America/Cayenne" },
    { name: "Cayman", id: "America/Cayman" },
    { name: "Chicago", id: "America/Chicago" },
    { name: "Chihuahua", id: "America/Chihuahua" },
    { name: "Coral Harbour", id: "America/Coral_Harbour" },
    { name: "Cordoba", id: "America/Cordoba" },
    { name: "Costa Rica", id: "America/Costa_Rica" },
    { name: "Creston", id: "America/Creston" },
    { name: "Cuiaba", id: "America/Cuiaba" },
    { name: "Curacao", id: "America/Curacao" },
    { name: "Danmarkshavn", id: "America/Danmarkshavn" },
    { name: "Dawson", id: "America/Dawson" },
    { name: "Dawson Creek", id: "America/Dawson_Creek" },
    { name: "Denver", id: "America/Denver" },
    { name: "Detroit", id: "America/Detroit" },
    { name: "Dominica", id: "America/Dominica" },
    { name: "Edmonton", id: "America/Edmonton" },
    { name: "Eirunepe", id: "America/Eirunepe" },
    { name: "El Salvador", id: "America/El_Salvador" },
    { name: "Ensenada", id: "America/Ensenada" },
    { name: "Fort Nelson", id: "America/Fort_Nelson" },
    { name: "Fort Wayne", id: "America/Fort_Wayne" },
    { name: "Fortaleza", id: "America/Fortaleza" },
    { name: "Glace Bay", id: "America/Glace_Bay" },
    { name: "Godthab", id: "America/Godthab" },
    { name: "Goose Bay", id: "America/Goose_Bay" },
    { name: "Grand Turk", id: "America/Grand_Turk" },
    { name: "Grenada", id: "America/Grenada" },
    { name: "Guadeloupe", id: "America/Guadeloupe" },
    { name: "Guatemala", id: "America/Guatemala" },
    { name: "Guayaquil", id: "America/Guayaquil" },
    { name: "Guyana", id: "America/Guyana" },
    { name: "Halifax", id: "America/Halifax" },
    { name: "Havana", id: "America/Havana" },
    { name: "Hermosillo", id: "America/Hermosillo" },
    { name: "Indianapolis", id: "America/Indiana/Indianapolis" },
    { name: "Knox", id: "America/Indiana/Knox" },
    { name: "Marengo", id: "America/Indiana/Marengo" },
    { name: "Petersburg", id: "America/Indiana/Petersburg" },
    { name: "Tell City", id: "America/Indiana/Tell_City" },
    { name: "Vevay", id: "America/Indiana/Vevay" },
    { name: "Vincennes", id: "America/Indiana/Vincennes" },
    { name: "Winamac", id: "America/Indiana/Winamac" },
    { name: "Indianapolis", id: "America/Indianapolis" },
    { name: "Inuvik", id: "America/Inuvik" },
    { name: "Iqaluit", id: "America/Iqaluit" },
    { name: "Jamaica", id: "America/Jamaica" },
    { name: "Jujuy", id: "America/Jujuy" },
    { name: "Juneau", id: "America/Juneau" },
    { name: "Louisville", id: "America/Kentucky/Louisville" },
    { name: "Monticello", id: "America/Kentucky/Monticello" },
    { name: "Knox IN", id: "America/Knox_IN" },
    { name: "Kralendijk", id: "America/Kralendijk" },
    { name: "La Paz", id: "America/La_Paz" },
    { name: "Lima", id: "America/Lima" },
    { name: "Los Angeles", id: "America/Los_Angeles" },
    { name: "Louisville", id: "America/Louisville" },
    { name: "Lower Princes", id: "America/Lower_Princes" },
    { name: "Maceio", id: "America/Maceio" },
    { name: "Managua", id: "America/Managua" },
    { name: "Manaus", id: "America/Manaus" },
    { name: "Marigot", id: "America/Marigot" },
    { name: "Martinique", id: "America/Martinique" },
    { name: "Matamoros", id: "America/Matamoros" },
    { name: "Mazatlan", id: "America/Mazatlan" },
    { name: "Mendoza", id: "America/Mendoza" },
    { name: "Menominee", id: "America/Menominee" },
    { name: "Merida", id: "America/Merida" },
    { name: "Metlakatla", id: "America/Metlakatla" },
    { name: "Mexico City", id: "America/Mexico_City" },
    { name: "Miquelon", id: "America/Miquelon" },
    { name: "Moncton", id: "America/Moncton" },
    { name: "Monterrey", id: "America/Monterrey" },
    { name: "Montevideo", id: "America/Montevideo" },
    { name: "Montreal", id: "America/Montreal" },
    { name: "Montserrat", id: "America/Montserrat" },
    { name: "Nassau", id: "America/Nassau" },
    { name: "New York", id: "America/New_York" },
    { name: "Nipigon", id: "America/Nipigon" },
    { name: "Nome", id: "America/Nome" },
    { name: "Noronha", id: "America/Noronha" },
    { name: "Beulah", id: "America/North_Dakota/Beulah" },
    { name: "Center", id: "America/North_Dakota/Center" },
    { name: "New Salem", id: "America/North_Dakota/New_Salem" },
    { name: "Nuuk", id: "America/Nuuk" },
    { name: "Ojinaga", id: "America/Ojinaga" },
    { name: "Panama", id: "America/Panama" },
    { name: "Pangnirtung", id: "America/Pangnirtung" },
    { name: "Paramaribo", id: "America/Paramaribo" },
    { name: "Phoenix", id: "America/Phoenix" },
    { name: "Porto Acre", id: "America/Porto_Acre" },
    { name: "Porto Velho", id: "America/Porto_Velho" },
    { name: "Puerto Rico", id: "America/Puerto_Rico" },
    { name: "Punta Arenas", id: "America/Punta_Arenas" },
    { name: "Recife", id: "America/Recife" },
    { name: "Regina", id: "America/Regina" },
    { name: "Resolute", id: "America/Resolute" },
    { name: "Rio Branco", id: "America/Rio_Branco" },
    { name: "Rosario", id: "America/Rosario" },
    { name: "Santa Isabel", id: "America/Santa_Isabel" },
    { name: "Santarem", id: "America/Santarem" },
    { name: "Santiago", id: "America/Santiago" },
    { name: "Santo Domingo", id: "America/Santo_Domingo" },
    { name: "Sao Paulo", id: "America/Sao_Paulo" },
    { name: "Scoresbysund", id: "America/Scoresbysund" },
    { name: "Shiprock", id: "America/Shiprock" },
    { name: "Sitka", id: "America/Sitka" },
    { name: "Tegucigalpa", id: "America/Tegucigalpa" },
    { name: "Thule", id: "America/Thule" },
    { name: "Thunder Bay", id: "America/Thunder_Bay" },
    { name: "Tijuana", id: "America/Tijuana" },
    { name: "Toronto", id: "America/Toronto" },
    { name: "Tortola", id: "America/Tortola" },
    { name: "Vancouver", id: "America/Vancouver" },
    { name: "Virgin", id: "America/Virgin" },
    { name: "Whitehorse", id: "America/Whitehorse" },
    { name: "Winnipeg", id: "America/Winnipeg" },
    { name: "Yakutat", id: "America/Yakutat" },
    { name: "Yellowknife", id: "America/Yellowknife" },
    { name: "Casey", id: "Antarctica/Casey" },
    { name: "Davis", id: "Antarctica/Davis" },
    { name: "DumontDUrville", id: "Antarctica/DumontDUrville" },
    { name: "Macquarie", id: "Antarctica/Macquarie" },
    { name: "Mawson", id: "Antarctica/Mawson" },
    { name: "McMurdo", id: "Antarctica/McMurdo" },
    { name: "Palmer", id: "Antarctica/Palmer" },
    { name: "Rothera", id: "Antarctica/Rothera" },
    { name: "South Pole", id: "Antarctica/South_Pole" },
    { name: "Syowa", id: "Antarctica/Syowa" },
    { name: "Troll", id: "Antarctica/Troll" },
    { name: "Vostok", id: "Antarctica/Vostok" },
    { name: "Longyearbyen", id: "Arctic/Longyearbyen" },
    { name: "Aden", id: "Asia/Aden" },
    { name: "Almaty", id: "Asia/Almaty" },
    { name: "Amman", id: "Asia/Amman" },
    { name: "Anadyr", id: "Asia/Anadyr" },
    { name: "Aqtau", id: "Asia/Aqtau" },
    { name: "Aqtobe", id: "Asia/Aqtobe" },
    { name: "Ashgabat", id: "Asia/Ashgabat" },
    { name: "Ashkhabad", id: "Asia/Ashkhabad" },
    { name: "Atyrau", id: "Asia/Atyrau" },
    { name: "Baghdad", id: "Asia/Baghdad" },
    { name: "Bahrain", id: "Asia/Bahrain" },
    { name: "Baku", id: "Asia/Baku" },
    { name: "Bangkok", id: "Asia/Bangkok" },
    { name: "Barnaul", id: "Asia/Barnaul" },
    { name: "Beirut", id: "Asia/Beirut" },
    { name: "Bishkek", id: "Asia/Bishkek" },
    { name: "Brunei", id: "Asia/Brunei" },
    { name: "Calcutta", id: "Asia/Calcutta" },
    { name: "Chita", id: "Asia/Chita" },
    { name: "Choibalsan", id: "Asia/Choibalsan" },
    { name: "Chongqing", id: "Asia/Chongqing" },
    { name: "Chungking", id: "Asia/Chungking" },
    { name: "Colombo", id: "Asia/Colombo" },
    { name: "Dacca", id: "Asia/Dacca" },
    { name: "Damascus", id: "Asia/Damascus" },
    { name: "Dhaka", id: "Asia/Dhaka" },
    { name: "Dili", id: "Asia/Dili" },
    { name: "Dubai", id: "Asia/Dubai" },
    { name: "Dushanbe", id: "Asia/Dushanbe" },
    { name: "Famagusta", id: "Asia/Famagusta" },
    { name: "Gaza", id: "Asia/Gaza" },
    { name: "Harbin", id: "Asia/Harbin" },
    { name: "Hebron", id: "Asia/Hebron" },
    { name: "Ho Chi Minh", id: "Asia/Ho_Chi_Minh" },
    { name: "Hong Kong", id: "Asia/Hong_Kong" },
    { name: "Hovd", id: "Asia/Hovd" },
    { name: "Irkutsk", id: "Asia/Irkutsk" },
    { name: "Istanbul", id: "Asia/Istanbul" },
    { name: "Jakarta", id: "Asia/Jakarta" },
    { name: "Jayapura", id: "Asia/Jayapura" },
    { name: "Jerusalem", id: "Asia/Jerusalem" },
    { name: "Kabul", id: "Asia/Kabul" },
    { name: "Kamchatka", id: "Asia/Kamchatka" },
    { name: "Karachi", id: "Asia/Karachi" },
    { name: "Kashgar", id: "Asia/Kashgar" },
    { name: "Kathmandu", id: "Asia/Kathmandu" },
    { name: "Katmandu", id: "Asia/Katmandu" },
    { name: "Khandyga", id: "Asia/Khandyga" },
    { name: "Kolkata", id: "Asia/Kolkata" },
    { name: "Krasnoyarsk", id: "Asia/Krasnoyarsk" },
    { name: "Kuala Lumpur", id: "Asia/Kuala_Lumpur" },
    { name: "Kuching", id: "Asia/Kuching" },
    { name: "Kuwait", id: "Asia/Kuwait" },
    { name: "Macao", id: "Asia/Macao" },
    { name: "Macau", id: "Asia/Macau" },
    { name: "Magadan", id: "Asia/Magadan" },
    { name: "Makassar", id: "Asia/Makassar" },
    { name: "Manila", id: "Asia/Manila" },
    { name: "Muscat", id: "Asia/Muscat" },
    { name: "Nicosia", id: "Asia/Nicosia" },
    { name: "Novokuznetsk", id: "Asia/Novokuznetsk" },
    { name: "Novosibirsk", id: "Asia/Novosibirsk" },
    { name: "Omsk", id: "Asia/Omsk" },
    { name: "Oral", id: "Asia/Oral" },
    { name: "Phnom Penh", id: "Asia/Phnom_Penh" },
    { name: "Pontianak", id: "Asia/Pontianak" },
    { name: "Pyongyang", id: "Asia/Pyongyang" },
    { name: "Qatar", id: "Asia/Qatar" },
    { name: "Qostanay", id: "Asia/Qostanay" },
    { name: "Qyzylorda", id: "Asia/Qyzylorda" },
    { name: "Rangoon", id: "Asia/Rangoon" },
    { name: "Riyadh", id: "Asia/Riyadh" },
    { name: "Saigon", id: "Asia/Saigon" },
    { name: "Sakhalin", id: "Asia/Sakhalin" },
    { name: "Samarkand", id: "Asia/Samarkand" },
    { name: "Seoul", id: "Asia/Seoul" },
    { name: "Shanghai", id: "Asia/Shanghai" },
    { name: "Singapore", id: "Asia/Singapore" },
    { name: "Srednekolymsk", id: "Asia/Srednekolymsk" },
    { name: "Taipei", id: "Asia/Taipei" },
    { name: "Tashkent", id: "Asia/Tashkent" },
    { name: "Tbilisi", id: "Asia/Tbilisi" },
    { name: "Tehran", id: "Asia/Tehran" },
    { name: "Tel Aviv", id: "Asia/Tel_Aviv" },
    { name: "Thimbu", id: "Asia/Thimbu" },
    { name: "Thimphu", id: "Asia/Thimphu" },
    { name: "Tokyo", id: "Asia/Tokyo" },
    { name: "Tomsk", id: "Asia/Tomsk" },
    { name: "Ujung Pandang", id: "Asia/Ujung_Pandang" },
    { name: "Ulaanbaatar", id: "Asia/Ulaanbaatar" },
    { name: "Ulan Bator", id: "Asia/Ulan_Bator" },
    { name: "Urumqi", id: "Asia/Urumqi" },
    { name: "Ust", id: "Asia/Ust-Nera" },
    { name: "Vientiane", id: "Asia/Vientiane" },
    { name: "Vladivostok", id: "Asia/Vladivostok" },
    { name: "Yakutsk", id: "Asia/Yakutsk" },
    { name: "Yangon", id: "Asia/Yangon" },
    { name: "Yekaterinburg", id: "Asia/Yekaterinburg" },
    { name: "Yerevan", id: "Asia/Yerevan" },
    { name: "Azores", id: "Atlantic/Azores" },
    { name: "Bermuda", id: "Atlantic/Bermuda" },
    { name: "Canary", id: "Atlantic/Canary" },
    { name: "Cape Verde", id: "Atlantic/Cape_Verde" },
    { name: "Faeroe", id: "Atlantic/Faeroe" },
    { name: "Faroe", id: "Atlantic/Faroe" },
    { name: "Jan Mayen", id: "Atlantic/Jan_Mayen" },
    { name: "Madeira", id: "Atlantic/Madeira" },
    { name: "Reykjavik", id: "Atlantic/Reykjavik" },
    { name: "South Georgia", id: "Atlantic/South_Georgia" },
    { name: "St Helena", id: "Atlantic/St_Helena" },
    { name: "Stanley", id: "Atlantic/Stanley" },
    { name: "Adelaide", id: "Australia/Adelaide" },
    { name: "Brisbane", id: "Australia/Brisbane" },
    { name: "Broken Hill", id: "Australia/Broken_Hill" },
    { name: "Canberra", id: "Australia/Canberra" },
    { name: "Currie", id: "Australia/Currie" },
    { name: "Darwin", id: "Australia/Darwin" },
    { name: "Eucla", id: "Australia/Eucla" },
    { name: "Hobart", id: "Australia/Hobart" },
    { name: "Lindeman", id: "Australia/Lindeman" },
    { name: "Lord Howe", id: "Australia/Lord_Howe" },
    { name: "Melbourne", id: "Australia/Melbourne" },
    { name: "North", id: "Australia/North" },
    { name: "Perth", id: "Australia/Perth" },
    { name: "Queensland", id: "Australia/Queensland" },
    { name: "South", id: "Australia/South" },
    { name: "Sydney", id: "Australia/Sydney" },
    { name: "Tasmania", id: "Australia/Tasmania" },
    { name: "Victoria", id: "Australia/Victoria" },
    { name: "West", id: "Australia/West" },
    { name: "Yancowinna", id: "Australia/Yancowinna" },
    { name: "Acre", id: "Brazil/Acre" },
    { name: "DeNoronha", id: "Brazil/DeNoronha" },
    { name: "East", id: "Brazil/East" },
    { name: "West", id: "Brazil/West" },
    { name: "Atlantic", id: "Canada/Atlantic" },
    { name: "Central", id: "Canada/Central" },
    { name: "Eastern", id: "Canada/Eastern" },
    { name: "Mountain", id: "Canada/Mountain" },
    { name: "Newfoundland", id: "Canada/Newfoundland" },
    { name: "Pacific", id: "Canada/Pacific" },
    { name: "Saskatchewan", id: "Canada/Saskatchewan" },
    { name: "Yukon", id: "Canada/Yukon" },
    { name: "Continental", id: "Chile/Continental" },
    { name: "EasterIsland", id: "Chile/EasterIsland" },
    { name: "Cuba", id: "Cuba" },
    { name: "Egypt", id: "Egypt" },
    { name: "Eire", id: "Eire" },
    { name: "Amsterdam", id: "Europe/Amsterdam" },
    { name: "Andorra", id: "Europe/Andorra" },
    { name: "Astrakhan", id: "Europe/Astrakhan" },
    { name: "Athens", id: "Europe/Athens" },
    { name: "Belfast", id: "Europe/Belfast" },
    { name: "Belgrade", id: "Europe/Belgrade" },
    { name: "Berlin", id: "Europe/Berlin" },
    { name: "Bratislava", id: "Europe/Bratislava" },
    { name: "Brussels", id: "Europe/Brussels" },
    { name: "Bucharest", id: "Europe/Bucharest" },
    { name: "Budapest", id: "Europe/Budapest" },
    { name: "Busingen", id: "Europe/Busingen" },
    { name: "Chisinau", id: "Europe/Chisinau" },
    { name: "Copenhagen", id: "Europe/Copenhagen" },
    { name: "Dublin", id: "Europe/Dublin" },
    { name: "Gibraltar", id: "Europe/Gibraltar" },
    { name: "Guernsey", id: "Europe/Guernsey" },
    { name: "Helsinki", id: "Europe/Helsinki" },
    { name: "Isle of Man", id: "Europe/Isle_of_Man" },
    { name: "Istanbul", id: "Europe/Istanbul" },
    { name: "Jersey", id: "Europe/Jersey" },
    { name: "Kaliningrad", id: "Europe/Kaliningrad" },
    { name: "Kiev", id: "Europe/Kiev" },
    { name: "Kirov", id: "Europe/Kirov" },
    { name: "Lisbon", id: "Europe/Lisbon" },
    { name: "Ljubljana", id: "Europe/Ljubljana" },
    { name: "London", id: "Europe/London" },
    { name: "Luxembourg", id: "Europe/Luxembourg" },
    { name: "Madrid", id: "Europe/Madrid" },
    { name: "Malta", id: "Europe/Malta" },
    { name: "Mariehamn", id: "Europe/Mariehamn" },
    { name: "Minsk", id: "Europe/Minsk" },
    { name: "Monaco", id: "Europe/Monaco" },
    { name: "Moscow", id: "Europe/Moscow" },
    { name: "Nicosia", id: "Europe/Nicosia" },
    { name: "Oslo", id: "Europe/Oslo" },
    { name: "Paris", id: "Europe/Paris" },
    { name: "Podgorica", id: "Europe/Podgorica" },
    { name: "Prague", id: "Europe/Prague" },
    { name: "Riga", id: "Europe/Riga" },
    { name: "Rome", id: "Europe/Rome" },
    { name: "Samara", id: "Europe/Samara" },
    { name: "San Marino", id: "Europe/San_Marino" },
    { name: "Sarajevo", id: "Europe/Sarajevo" },
    { name: "Saratov", id: "Europe/Saratov" },
    { name: "Simferopol", id: "Europe/Simferopol" },
    { name: "Skopje", id: "Europe/Skopje" },
    { name: "Sofia", id: "Europe/Sofia" },
    { name: "Stockholm", id: "Europe/Stockholm" },
    { name: "Tallinn", id: "Europe/Tallinn" },
    { name: "Tirane", id: "Europe/Tirane" },
    { name: "Tiraspol", id: "Europe/Tiraspol" },
    { name: "Ulyanovsk", id: "Europe/Ulyanovsk" },
    { name: "Uzhgorod", id: "Europe/Uzhgorod" },
    { name: "Vaduz", id: "Europe/Vaduz" },
    { name: "Vatican", id: "Europe/Vatican" },
    { name: "Vienna", id: "Europe/Vienna" },
    { name: "Vilnius", id: "Europe/Vilnius" },
    { name: "Volgograd", id: "Europe/Volgograd" },
    { name: "Warsaw", id: "Europe/Warsaw" },
    { name: "Zagreb", id: "Europe/Zagreb" },
    { name: "Zaporozhye", id: "Europe/Zaporozhye" },
    { name: "Zurich", id: "Europe/Zurich" },
    { name: "Greenwich", id: "Greenwich" },
    { name: "Hongkong", id: "Hongkong" },
    { name: "Iceland", id: "Iceland" },
    { name: "Antananarivo", id: "Indian/Antananarivo" },
    { name: "Chagos", id: "Indian/Chagos" },
    { name: "Christmas", id: "Indian/Christmas" },
    { name: "Cocos", id: "Indian/Cocos" },
    { name: "Comoro", id: "Indian/Comoro" },
    { name: "Kerguelen", id: "Indian/Kerguelen" },
    { name: "Mahe", id: "Indian/Mahe" },
    { name: "Maldives", id: "Indian/Maldives" },
    { name: "Mauritius", id: "Indian/Mauritius" },
    { name: "Mayotte", id: "Indian/Mayotte" },
    { name: "Reunion", id: "Indian/Reunion" },
    { name: "Iran", id: "Iran" },
    { name: "Israel", id: "Israel" },
    { name: "Jamaica", id: "Jamaica" },
    { name: "Japan", id: "Japan" },
    { name: "Kwajalein", id: "Kwajalein" },
    { name: "Libya", id: "Libya" },
    { name: "BajaNorte", id: "Mexico/BajaNorte" },
    { name: "BajaSur", id: "Mexico/BajaSur" },
    { name: "General", id: "Mexico/General" },
    { name: "Navajo", id: "Navajo" },
    { name: "Apia", id: "Pacific/Apia" },
    { name: "Auckland", id: "Pacific/Auckland" },
    { name: "Bougainville", id: "Pacific/Bougainville" },
    { name: "Chatham", id: "Pacific/Chatham" },
    { name: "Chuuk", id: "Pacific/Chuuk" },
    { name: "Easter", id: "Pacific/Easter" },
    { name: "Efate", id: "Pacific/Efate" },
    { name: "Enderbury", id: "Pacific/Enderbury" },
    { name: "Fakaofo", id: "Pacific/Fakaofo" },
    { name: "Fiji", id: "Pacific/Fiji" },
    { name: "Funafuti", id: "Pacific/Funafuti" },
    { name: "Galapagos", id: "Pacific/Galapagos" },
    { name: "Gambier", id: "Pacific/Gambier" },
    { name: "Guadalcanal", id: "Pacific/Guadalcanal" },
    { name: "Guam", id: "Pacific/Guam" },
    { name: "Honolulu", id: "Pacific/Honolulu" },
    { name: "Johnston", id: "Pacific/Johnston" },
    { name: "Kanton", id: "Pacific/Kanton" },
    { name: "Kiritimati", id: "Pacific/Kiritimati" },
    { name: "Kosrae", id: "Pacific/Kosrae" },
    { name: "Kwajalein", id: "Pacific/Kwajalein" },
    { name: "Majuro", id: "Pacific/Majuro" },
    { name: "Marquesas", id: "Pacific/Marquesas" },
    { name: "Midway", id: "Pacific/Midway" },
    { name: "Nauru", id: "Pacific/Nauru" },
    { name: "Niue", id: "Pacific/Niue" },
    { name: "Norfolk", id: "Pacific/Norfolk" },
    { name: "Noumea", id: "Pacific/Noumea" },
    { name: "Pago Pago", id: "Pacific/Pago_Pago" },
    { name: "Palau", id: "Pacific/Palau" },
    { name: "Pitcairn", id: "Pacific/Pitcairn" },
    { name: "Pohnpei", id: "Pacific/Pohnpei" },
    { name: "Ponape", id: "Pacific/Ponape" },
    { name: "Port Moresby", id: "Pacific/Port_Moresby" },
    { name: "Rarotonga", id: "Pacific/Rarotonga" },
    { name: "Saipan", id: "Pacific/Saipan" },
    { name: "Samoa", id: "Pacific/Samoa" },
    { name: "Tahiti", id: "Pacific/Tahiti" },
    { name: "Tarawa", id: "Pacific/Tarawa" },
    { name: "Tongatapu", id: "Pacific/Tongatapu" },
    { name: "Truk", id: "Pacific/Truk" },
    { name: "Wake", id: "Pacific/Wake" },
    { name: "Wallis", id: "Pacific/Wallis" },
    { name: "Yap", id: "Pacific/Yap" },
    { name: "Poland", id: "Poland" },
    { name: "Portugal", id: "Portugal" },
    { name: "Singapore", id: "Singapore" },
    { name: "Turkey", id: "Turkey" },
    { name: "Alaska", id: "US/Alaska" },
    { name: "Aleutian", id: "US/Aleutian" },
    { name: "Arizona", id: "US/Arizona" },
    { name: "Central", id: "US/Central" },
    { name: "East", id: "US/East-Indiana" },
    { name: "Eastern", id: "US/Eastern" },
    { name: "Hawaii", id: "US/Hawaii" },
    { name: "Indiana", id: "US/Indiana-Starke" },
    { name: "Michigan", id: "US/Michigan" },
    { name: "Mountain", id: "US/Mountain" },
    { name: "Pacific", id: "US/Pacific" },
    { name: "Samoa", id: "US/Samoa" },
    { name: "Universal", id: "Universal" },
    { name: "Zulu", id: "Zulu" }
];
